export const INIT_PAGE_LIST = 'home/init_page_list'
export const GET_PAGE_LIST = 'home/get_page_list'
export const INIT_CATEGORY_LIST = 'home/init_category_list'
export const GET_CATEGORY_LIST = 'home/get_category_list'
export const ADD_PAGE_LIST = 'home/add_page_list'
export const TOGGLE_SCROLL_TOP = 'home/toggle_scroll_top'
