export const INPUT_FOCUS = 'header/input_focus'
export const INPUT_BLUR = 'header/input_blur'
export const SET_LIST = 'header/set_list'
export const GET_LIST = 'header/get_list'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'